{% extends 'base.html.twig' %}

{% block title %}Item index{% endblock %}



{% block body %}

    <h1>Página Principal</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Description</th>
                <th>Amount</th>
                <th>Hallway</th>
                <th>Rack</th>
                <th>Self</th>
            </tr>
        </thead>
        <tbody>
        {% for item in items %}
            <tr>
                <td>{{ item.id }}</td>
                <td>{{ item.description }}</td>
                <td>{{ item.amount }}</td>
                <td>{{ item.location.hallway }}</td>
                <td>{{ item.location.rack }}</td>
                <td>{{ item.location.shelf }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}



{# {% extends 'base.html.twig' %}

{% block title %}Hello MainController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code>C:/Users/coson/Documents/REPOSITORIOS_GITHUB/DWES/pruebaSymfony/src/Controller/MainController.php</code></li>
        <li>Your template at <code>C:/Users/coson/Documents/REPOSITORIOS_GITHUB/DWES/pruebaSymfony/templates/main/index.html.twig</code></li>
    </ul>
</div>
{% endblock %} #}
